.TH SFEED 1 sfeed\-0.9
.SH NAME
sfeed_frames \- format feeds file (TSV) from sfeed_update to HTML with frames
.SH SYNOPSIS
.B sfeed_frames
.RB [path]
.SH OPTIONS
.TP
.B [path]
Path to write files to, default is ".". On success path will contain the
files: index.html which is the main HTML file with the frames,
items.html which contains all the items as HTML links to the local content,
menu.html which contains navigation anchor links with the feed names
(to items.html).
.SH FILE STRUCTURE
Directory for each feed category in the format: path/feedname/itemname.html.
The feedname and item names are normalized, whitespace characters are replaced
with a \-, multiple whitespace is replaced by a single \- and trailing
whitespace is ignored.
.SH DESCRIPTION
Format feeds file (TSV) from sfeed_update to HTML. It reads TSV data from
stdin and writes HTML to the specified directory. For the exact TSV format
see sfeed_update(1).
.SH SEE ALSO
.BR sfeed_plain(1)
.BR sfeed_update(1)
.BR sfeed(1)
.SH BUGS
Please report them!
