.TH SFEED 1 sfeed\-0.9
.SH NAME
sfeed_web \- find urls to feeds from a webpage
.SH SYNOPSIS
.B sfeed_web
.RB [baseurl]
.SH OPTIONS
.TP
.B [baseurl]
Optional baseurl if site uses relative urls to feed.
.SH DESCRIPTION
It reads the HTML website as XML data from stdin and writes the found urls to
stdout in the format:

content\-type<space>url

content\-type is usually: application/atom+xml or application/rss+xml
.SH EXAMPLES
.TP
Get urls from xkcd website:
.nf
wget http://www.xkcd.com -q -O - | sfeed_web "http://www.xkcd.com/"
.SH BUGS
Please report them!
