.Dd December 25, 2014
.Dt SFEED_HTML 1
.Os
.Sh NAME
.Nm sfeed_html
.Nd formats a feeds file to HTML
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
formats a feeds file (TSV) from
.Xr sfeed_update 1
to HTML. It reads TSV data from stdin and writes HTML to stdout. For the exact TSV format see
.Xr sfeed_update 1 .
.Sh SEE ALSO
.Xr sfeed_plain 1 ,
.Xr sfeed_update 1 ,
.Xr sfeed 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
