.Dd August 22, 2018
.Dt SFEED_TAIL 1
.Os
.Sh NAME
.Nm sfeed_tail
.Nd format unseen feed data to a plain-text list
.Sh SYNOPSIS
.Nm
.Ar file...
.Sh DESCRIPTION
.Nm
formats only new and unseen feed data (TSV) from
one or more
.Ar file
to stdout as a plain-text list.
The basename of the
.Ar file
is used as the feed name in the output.
.Pp
Unseen items are printed per line in a similar format to
.Xr sfeed_plain 1 ,
duplicate items are ignored.
The list of unique items is determined by the fields: item id, item link and
UNIX timestamp of the item date.
.Pp
.Nm
will also only process and show items that are considered new: the item
timestamp is not older than a day ago.
.Sh IMPLEMENTATION NOTES
.Nm
checks for file modifications each second by checking the filesize and
modification time.
Keep in mind that because
.Nm
keeps a list of items it can potentially consume much memory.
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_plain 1 ,
.Xr tail 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
