.Dd December 25, 2014
.Dt SFEED_UPDATE 1
.Os
.Sh NAME
.Nm sfeed_update
.Nd update feeds and merge with old feeds
.Sh SYNOPSIS
.Nm
.Op Ar configfile
.Sh DESCRIPTION
.Nm
updates feeds files and merges the new data with the previous files. These
are the files in the directory
.Pa $HOME/.sfeed/feeds
by default.
.Sh OPTIONS
.Bl -tag -width 17n
.It Ar configfile
config file, if not specified uses the path
.Pa $HOME/.sfeed/sfeedrc
by default. See the
.Sx FILES READ
section for more information.
.El
.Sh FILES READ
.Bl -tag -width 17n
.It Ar sfeedrc
Config file, see the sfeedrc.example file for an example.
This file is evaluated as a shellscript in
.Nm .
You can for example override the fetchfeed() function to
use
.Xr curl 1 ,
.Xr wget 1 ,
or an other network downloader or you can override the merge() function to
change the merge logic. The function feeds() is called to fetch the feeds. By
default the function feed() is executed as a parallel job to speedup updating.
.El
.Sh FILES WRITTEN
.Bl -tag -width 17n
.It Ar feedname
Tab-separated format containing all items per feed.
The sfeed_update script merges new items with this file.
.It Ar feedname.new
Temporary file used by sfeed_update to merge items.
.El
.Sh EXAMPLES
To update your feeds and format them in various formats:
.Bd -literal
# Update
sfeed_update "configfile"
# Plain-text list
sfeed_plain $HOME/.sfeed/feeds/* > $HOME/.sfeed/feeds.txt
# HTML
sfeed_html $HOME/.sfeed/feeds/* > $HOME/.sfeed/feeds.html
# HTML with frames
mkdir -p somedir && cd somedir && sfeed_frames $HOME/.sfeed/feeds/*
.Ed
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_html 1 ,
.Xr sfeed_plain 1 ,
.Xr sh 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
