.Dd January 25, 2019
.Dt SFEED_UPDATE 1
.Os
.Sh NAME
.Nm sfeed_update
.Nd update feeds and merge with old feeds
.Sh SYNOPSIS
.Nm
.Op Ar sfeedrc
.Sh DESCRIPTION
.Nm
updates feeds files and merges the new data with the previous files.
These are the files in the directory
.Pa $HOME/.sfeed/feeds
by default.
.Sh OPTIONS
.Bl -tag -width 17n
.It Ar sfeedrc
Config file, if not specified uses the path
.Pa $HOME/.sfeed/sfeedrc
by default.
See the
.Sx FILES READ
section for more information.
.El
.Sh FILES READ
.Bl -tag -width 17n
.It Ar sfeedrc
Config file, see the sfeedrc.example file for an example.
This file is evaluated as a shellscript in
.Nm .
.Pp
Atleast the following functions can be overridden per feed:
.Bl -tag -width 17n
.It Fn fetch
to use
.Xr wget 1 ,
OpenBSD
.Xr ftp 1
or an other download program.
.It Fn merge
to change the merge logic.
.It Fn filter
to filter on fields.
.It Fn order
to change the sort order.
.El
.Pp
The
.Fn feeds
function is called to process the feeds.
The default
.Fn feed
function is executed concurrently as a background job in your
.Xr sfeedrc 5
config file to make updating faster.
The variable
.Va maxjobs
can be changed to limit or increase the amount of concurrent jobs (8 by
default).
.El
.Sh FILES WRITTEN
.Bl -tag -width 17n
.It feedname
TAB-separated format containing all items per feed.
The
.Nm
script merges new items with this file.
.It feedname.new
Temporary file used by
.Nm
to merge items.
.El
.Sh EXAMPLES
To update your feeds and format them in various formats:
.Bd -literal
# Update
sfeed_update "configfile"
# Plain-text list
sfeed_plain $HOME/.sfeed/feeds/* > $HOME/.sfeed/feeds.txt
# HTML
sfeed_html $HOME/.sfeed/feeds/* > $HOME/.sfeed/feeds.html
# HTML with frames
mkdir -p somedir && cd somedir && sfeed_frames $HOME/.sfeed/feeds/*
.Ed
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_html 1 ,
.Xr sfeed_plain 1 ,
.Xr sh 1 ,
.Xr sfeedrc 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
