.Dd December 25, 2014
.Dt SFEED_WEB 1
.Os
.Sh NAME
.Nm sfeed_web
.Nd finds urls to feeds from a HTML webpage
.Sh SYNOPSIS
.Nm
.Op Ar baseurl
.Sh DESCRIPTION
.Nm
reads the HTML website as XML or HTML data from stdin and writes the found
urls to stdout.
.Sh OPTIONS
.Bl -tag -width 8n
.It Ar baseurl
optional base url to use for found feed urls that are relative.
.El
.Sh OUTPUT FORMAT
content\-type<space>url<newline>
.Bl -tag -width 13n
.It Ar content\-type
Usually application/atom+xml or application/rss+xml.
.It Ar url
Found url to the feed. If the url is relative and the baseurl option is
specified then the url is changed accordingly.
.El
.Sh EXAMPLES
Get urls from xkcd website:
.Bd -literal
wget http://www.xkcd.com -q -O - | sfeed_web "http://www.xkcd.com/"
.Ed
.Sh SEE ALSO
.Xr sfeed_update 1 ,
.Xr sh 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
