.TH SFEED 1 sfeed\-0.9
.SH NAME
sfeed_opml_export \- generate an opml file based on a sfeedrc config file
.SH SYNOPSIS
.B sfeed_opml_export
.RB [configfile]
.SH OPTIONS
.TP
.B [configfile]
config file, if not specified uses the location $HOME/.sfeed/sfeedrc by default (see FILES READ section for more information).
.SH DESCRIPTION
Parse the specified config file and output opml XML data to stdout.
.SH SEE ALSO
.BR sfeed_update(1)
.SH BUGS
Please report them!
