.TH SFEED 1 sfeed\-VERSION
.SH NAME
sfeed_opml_config \- generate a sfeedrc config file based on an opml file
.SH SYNOPSIS
.B sfeed_opml_config
.SH DESCRIPTION
Reads the opml XML data from stdin and writes the config file text to stdout.
.SH SEE ALSO
.BR sfeed_update(1)
.SH BUGS
Please report them!
