.TH SFEED 1 sfeed\-VERSION
.SH NAME
sfeed_plain \- format feeds file (TSV) from sfeed_update to plain text
.SH SYNOPSIS
.B sfeed
.SH DESCRIPTION
Format feeds file (TSV) from sfeed_update to plain text. Reads TSV data from
stdin and writes plain text to stdout. For the exact TSV format see
sfeed_update(1).
.SH SEE ALSO
.BR sfeed_html(1)
.BR sfeed_update(1)
.BR sfeed(1)
.SH BUGS
Please report them!
