.Dd December 25, 2014
.Dt SFEED 1
.Os
.Sh NAME
.Nm sfeed
.Nd simple RSS and Atom parser
.Sh SYNOPSIS
.Nm
.Op Ar baseurl
.Sh DESCRIPTION
.Nm
reads RSS or Atom feed data (XML) from stdin. It writes the feed data in a
tab-separated format to stdout. A
.Ar baseurl
can be specified if the links in the feed are relative urls and the baseurl of
the content differs from the feed. It is generally recommended to always have
absolute urls in your feeds, but the web sucks.
.Sh TAB-SEPARATED FORMAT FIELDS
The items are saved in a TSV-like format except newlines, tabs and
backslash are escaped with \\ (\\n, \\t and \\\\). Carriage returns (\\r) are
removed.
.Pp
The order and format of the fields are:
.Bl -tag -width 17n
.It Ar item timestamp
string, UNIX timestamp in GMT+0
.It Ar item timestamp
string, date and time in the format: YYYY-mm-dd HH:MM:SS tzname[[+-][HHMM]]
.It Ar item title
string
.It Ar item link
string, made to absolute url, unsafe characters are encoded
.It Ar item content
string
.It Ar item content\-type
string, "html" or "plain"
.It Ar item id
string
.It Ar item author
string
.It Ar feed type
string, "rss" or "atom"
.El
.Sh SEE ALSO
.Xr sfeed_plain 1 ,
.Xr sfeed_update 1 ,
.Xr sh 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
