.Dd December 25, 2014
.Dt SFEED_PLAIN 1
.Os
.Sh NAME
.Nm sfeed_plain
.Nd formats a feeds file to plain text
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
formats a feeds file (TSV) from
.Xr sfeed_update 1
to plain text. It reads TSV data from stdin and writes formatted plain text to
stdout. For the exact TSV format see
.Xr sfeed_update 1 .
.Sh SEE ALSO
.Xr sfeed 1 ,
.Xr sfeed_html 1 ,
.Xr sfeed_update 1
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
