.TH "SFEED_XMLENC" "1" "December 25, 2014" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_xmlenc\fR
\- get text\-encoding from XML
.SH "SYNOPSIS"
.HP 13n
\fBsfeed_xmlenc\fR
.SH "DESCRIPTION"
\fBsfeed_xmlenc\fR
reads XML data from stdin and writes the found text\-encoding to stdout.
.SH "EXAMPLES"
Get text\-encoding from xkcd Atom feed:
.nf
.sp
.RS 0n
wget http://www.xkcd.com/atom.xml -q -O - | sfeed_xmlenc
.RE
.fi
.SH "SEE ALSO"
sh(1),
sfeed_update(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
