.TH "SFEED_WEB" "1" "December 25, 2014" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_web\fR
\- finds urls to feeds from a HTML webpage
.SH "SYNOPSIS"
.HP 10n
\fBsfeed_web\fR
[\fIbaseurl\fR]
.SH "DESCRIPTION"
\fBsfeed_web\fR
reads the HTML website as XML or HTML data from stdin and writes the found
urls to stdout.
.SH "OPTIONS"
.TP 10n
\fIbaseurl\fR
optional base url to use for found feed urls that are relative.
.SH "OUTPUT FORMAT"
content\-type<space>url<newline>
.TP 15n
\fIcontent\-type\fR
Usually application/atom+xml or application/rss+xml.
.TP 15n
\fIurl\fR
Found url to the feed. If the url is relative and the baseurl option is
specified then the url is changed accordingly.
.SH "EXAMPLES"
Get urls from xkcd website:
.nf
.sp
.RS 0n
wget http://www.xkcd.com -q -O - | sfeed_web "http://www.xkcd.com/"
.RE
.fi
.SH "SEE ALSO"
sfeed_update(1),
sh(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
