.TH "SFEED_HTML" "1" "December 25, 2014" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_html\fR
\- formats a feeds file to HTML
.SH "SYNOPSIS"
.HP 11n
\fBsfeed_html\fR
.SH "DESCRIPTION"
\fBsfeed_html\fR
formats a feeds file (TSV) from
sfeed_update(1)
to HTML. It reads TSV data from stdin and writes HTML to stdout. For the exact TSV format see
sfeed_update(1).
.SH "SEE ALSO"
sfeed(1),
sfeed_plain(1),
sfeed_update(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
