.TH "SFEED_MAIL" "1" "May 17, 2015" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_mail\fR
\- formats a feeds file to mail
.SH "SYNOPSIS"
.HP 11n
\fBsfeed_mail\fR
.SH "DESCRIPTION"
\fBsfeed_mail\fR
formats a feeds file (TSV) from
sfeed_update(1)
to mail. It reads TSV data from stdin and writes e-mails to stdout. These can
be further processed by tools like
procmail(1).
.SH "FORMAT"
Depending on the original content\-type the mail will be formatted as
plain-text (text/plain) or HTML (text/html).
.SH "CUSTOM HEADERS"
To make filtering simpler some custom headers are set:
.TP 8n
X-feedname
The feedname (set in sfeedrc).
.SH "SEE ALSO"
procmail(1),
sfeed(1),
sfeed_update(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
