.TH "SFEED_OPML_EXPORT" "1" "December 25, 2014" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_opml_export\fR
\- generate an OPML file based on a sfeedrc config file
.SH "SYNOPSIS"
.HP 18n
\fBsfeed_opml_export\fR
[\fIconfig\ file\fR]
.SH "DESCRIPTION"
\fBsfeed_opml_export\fR
parses the specified config file and output OPML XML data to stdout.
.SH "OPTIONS"
.TP 19n
[config file]
default: "$HOME/.sfeed/sfeedrc", see the
sfeed_update(1)
\fIFILES READ\fR
section for more information.
.SH "SEE ALSO"
sfeed_update(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
