.TH "SFEED" "1" "December 25, 2014" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed\fR
\- simple RSS and Atom parser
.SH "SYNOPSIS"
.HP 6n
\fBsfeed\fR
[\fIsuffix\ string\fR]
.SH "DESCRIPTION"
\fBsfeed\fR
reads RSS or Atom feed data (XML) from stdin. It writes the feed data in a
tab-separated format to stdout.
.SH "TAB-SEPARATED FORMAT FIELDS"
The items are saved in a TSV-like format except newlines, tabs and
backslash are escaped with \\ (\\n, \\t and \\\\). Carriage returns (\\r) are
removed.
.PP
The order and format of the fields are:
.TP 19n
\fIitem timestamp\fR
string, UNIX timestamp in GMT+0
.TP 19n
\fIitem timestamp\fR
string, date and time in the format: YYYY-mm-dd HH:MM:SS tzname[+-]HHMM
.TP 19n
\fIitem title\fR
string
.TP 19n
\fIitem link\fR
string
.TP 19n
\fIitem content\fR
string
.TP 19n
\fIitem content\-type\fR
.br
string, "html" or "plain"
.TP 19n
\fIitem id\fR
string
.TP 19n
\fIitem author\fR
string
.TP 19n
\fIfeed type\fR
string, "rss" or "atom"
.SH "SEE ALSO"
sh(1),
sfeed_update(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
