.TH "SFEED_PLAIN" "1" "December 25, 2014" "" "General Commands Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_plain\fR
\- formats a feeds file to plain text
.SH "SYNOPSIS"
.HP 12n
\fBsfeed_plain\fR
.SH "DESCRIPTION"
\fBsfeed_plain\fR
formats a feeds file (TSV) from
sfeed_update(1)
to plain text. It reads TSV data from stdin and writes formatted plain text to
stdout. For the exact TSV format see
sfeed_update(1).
.SH "SEE ALSO"
sfeed_html(1),
sfeed_update(1),
sfeed(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
.sp
