.TH "SFEED_OPML_IMPORT" "1" "December 25, 2014" "" "OpenBSD Reference Manual"
.nh
.if n .ad l
.SH "NAME"
\fBsfeed_opml_import\fR
\- generate a sfeedrc config file based on an OPML file
.SH "SYNOPSIS"
.HP 18n
\fBsfeed_opml_import\fR
.SH "DESCRIPTION"
\fBsfeed_opml_import\fR
reads the OPML XML data from stdin and writes the config file text to stdout.
.SH "SEE ALSO"
sfeed_update(1)
.SH "AUTHORS"
Hiltjo Posthuma <\fIhiltjo@codemadness.org\fR>
